project:
  type: website
  output-dir: "."

website:
  title: "STICS Evaluation Dashboard"
  sidebar:
    style: docked
    contents:
      - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
