#' Run Stics simulations for a text workspace.
#'
#' @description
#' Runs Stics simulations for the USMs found in \code{usms_workspace} (a
#' text workspace as generated by \code{\link{gen_workspace_from_sms}}),
#' and saves the resulting simulation and observation data as
#' \code{.rds} files in \code{output_dir}. The saved files can later be
#' reused as \code{sim_rds}/\code{ref_sim_rds} and \code{obs_rds} in a
#' \code{\link{Configuration}}, bypassing the need to run simulations
#' or extract observations again.
#'
#' @param stics_exe path to the Stics executable
#' @param usms_workspace path to the Stics text workspace containing the
#'  USMs to simulate
#' @param metadata_file path to the metadata CSV file describing USM
#'  rotations (successive USMs), as used by \code{\link{Configuration}}
#' @param output_dir directory where the simulation results
#'  (\code{simulations.rds}) and observation data (\code{observations.rds})
#'  will be written. Created if it doesn't exist.
#' @param usms_files character vector of one or more paths to text files,
#'  each containing one USM name per line. If NULL (default), all USMs
#'  found in \code{usms_workspace} are simulated.
#' @param parallel Boolean. Is the computation to be done in parallel ?
#' @param cores Number of cores to use for parallel computation
#'
#' @returns invisibly, a list with two elements: \code{sim} and \code{obs},
#'  each a list of results (one tibble per USM), as returned by
#'  \code{SticsOnR::stics_wrapper} and \code{SticsRFiles::get_obs}
#'  respectively
#'
#' @export
run_simulations <- function(
  stics_exe,
  usms_workspace,
  metadata_file,
  output_dir,
  usms_files = NULL,
  parallel = FALSE,
  cores = NA
) {
  logger::log_info("Running simulations...")
  usms <- get_usms_to_simulate(usms_workspace, usms_files)

  logger::log_info("Found {length(usms)} USMs in {usms_workspace}")

  config <- Configuration$new(
    stics_exe = stics_exe,
    usms_workspace = usms_workspace,
    metadata_file = metadata_file,
    output_dir = output_dir,
    parallel = parallel,
    cores = cores
  )
  config$check_filesystem()

  obs <- get_obs_files(usms_workspace, usms, parallel, cores)
  vars <- get_var_from_obs(obs)

  workspace <- USMSWorkspace$new(config = config)
  sim <- workspace$run_simulations(usms, var = vars)

  logger::log_info(
    "Simulations done. Exporting sim and obs data to {output_dir}..."
  )

  prepare_output_dir(output_dir)
  save_rds(sim, output_dir, "simulations.rds")
  save_rds(obs, output_dir, "observations.rds")

  invisible(list(sim = sim, obs = obs))
}


save_rds <- function(data, output_dir, file_name) {
  out_file <- file.path(output_dir, file_name)
  saveRDS(data, out_file)
  logger::log_info("Data written to ", out_file)
}


get_usms_to_simulate <- function(usms_workspace, usms_files) {
  all_usms <- list.dirs(usms_workspace, full.names = FALSE, recursive = FALSE)
  if (is.null(usms_files)) {
    return(all_usms)
  }

  wanted_usms <- read_usms_files(usms_files)
  missing_usms <- setdiff(wanted_usms, all_usms)
  if (length(missing_usms) > 0) {
    stop(
      "The following USMs are not found in the workspace: ",
      toString(missing_usms), call. = FALSE
    )
  }
  wanted_usms
}


get_obs_files <- function(usms_workspace, usms, parallel, cores) {
  SticsRFiles::get_obs(
    workspace = usms_workspace,
    usm = usms,
    verbose = is_debug(),
    parallel = parallel,
    cores = cores
  )
}


get_var_from_obs <- function(obs) {
  var2exclude <- c("Date", "situation", "species", "version", "Plant")
  setdiff(unique(unlist(lapply(obs, names))), var2exclude)
}
