name: Lint
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libcurl4-openssl-dev libx11-dev libxslt-dev

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        env:
          RENV_CONFIG_CACHE_SYMLINKS: "TRUE"

      - name: Install lint deps
        run: |
          install.packages(c("lintr", "cyclocomp"))
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Run lintr
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true