name: Lint
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-r-renv

      - name: Install lint deps
        run: |
          install.packages(c("lintr", "cyclocomp"))
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Run lintr
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true